# Generated by Django 2.0.6 on 2018-06-07 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALbum',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=250)),
                ('albumTitle', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('albumImage', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=15)),
                ('songTitle', models.CharField(max_length=100)),
                ('album', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='first_app.ALbum')),
            ],
        ),
    ]
